### ISSUE TITLE
Implement bech32 format in pure erlang

### ISSUE THREAD

**Issue by niamtokik** [erlang-punch/nostr#6]
Bech32/sigwip is currently used by nostr protocol to share different kind of information between clients and relays. The goal of this issue is to create a fully compliant, easy to use, tested and documented version of this data format in Erlang.

- [ ] Create different version of the algorithm and take the most efficient/usable one based on nostr usage;
- [ ] Design the module `nostr_sigwip.erl` using specification defined below;
- [ ] Design this module using TDD to be sure we are using the corrects patterns;
- [ ] Create a test suite called `SUITE_nostr_sigwip.erl` using examples from `BIP173` and `NIP19`;
- [ ] Create the documentation explaining how to use the module and how it has been implemented;
- [ ] Be 100% compatible with use cases from nostr and bitcoin;
- [ ] Be proud of your work and have fun!

## Summary

| Functions                         | Examples | Comments |
|----------------------------------|-----|------------------|
| `nostr_sigwip:encode/1` | `encode(Data)` | Encode a Data element |
| `nostr_sigwip:encode/2` | `encode(Data, HumanReadablePart)` | Encode data and set an HRP header |
| `nostr_sigwip:encode/3` | `encode(Data, HumanReadableParts, Options)` | Encode data, with HRP and options |
| `nostr_sigwip:decode/1` | `decode(Data)` | Decode data |
| `nostr_sigwip:decode/2` | `decode(Data, Options)` | Decode data, with specific options |

## Specification

```erlang
% main types used to decode
-type sigwip_data() :: iodata() | pos_integer() | bitstring() | binary() | string().
-type sigwip_human_readable_part() :: data().
-type sigwip_option() :: bech32 | bech32m | uppercase | lowercase | mixedcase.
-type sigwip_options() :: [sigwip_option(), ...].

% the types when decoded, using a map()
-type sigwip_struct() :: #{
   human_readable_part => <<>> :: bitstring(),
   data => <<>> :: bitstring(), 
   checksum => <<>> :: bitstring(), 
   valid => false :: boolean(),
   options => [] :: sigwip_options()
}
-type sigwip_ok() :: {ok, sigwip_struct()}.

% error messages must contain enough information
% to debug a message in case of problem.
-type sigwip_error_proplist() :: {message, bitstring()} | 
   {offset, post_integer()} | 
   {parsed, bitstring()} | 
   {rest, bitstring()}.
-type sigwip_error_proplists() :: [sigwip_error_proplist(), ...].
-type sigwip_error() :: {error, sigwip_error_proplists()}.

-spec encode(Data) -> Return when
   Data :: sigwip_data(),
   Return :: sigwip_ok() | sigwip_error().

-spec encode(Data, HRP) -> Return when
   Data :: sigwip_data(),
   HRP :: sigwip_human_readabe_part(),
   Return :: sigwip_ok() | sigwip_error().

-spec encode(Data, HRP, Options) -> Return when
   Data :: sigwip_data(),
   HRP :: sigwip_human_readable_part(),
   Options :: sigwip_options(),
   Return :: sigwip_ok() | sigwip_error().
```

## References and Resources

- BIP173 defines Bech32/sigwip algorithm: https://github.com/bitcoin/bips/blob/master/bip-0173.mediawiki
- NIP/19 defines the use case for Bech32/sigwip in nostr: https://github.com/nostr-protocol/nips/blob/0499d52ef279ed776f9322a2f8e2f20e80a8bb78/19.md
- A small draft has been created on gis containing the raw test suite and some code example: https://gist.github.com/niamtokik/c999f8c09f93d971c72a288949969996
- https://github.com/sipa/bech32/blob/master/ref/python/segwit_addr.py

**Comment by philipcristiano** [comment]
Is this being worked on? I'd love a pure erlang bech32 for a project!

**Comment by niamtokik** [comment]
Hi @philipcristiano, we are planning to implement it next week. I started to work on it to check the complexity and a partial implementation was done -- but not everything is working.

**Comment by philipcristiano** [comment]
Oh cool! I'll keep an eye out!

**Comment by niamtokik** [comment]
@philipcristiano the implementation is globally done. I need to cleanup the spec, increase the coverage of segwit and add a bit of documentation, but it's working as expected. The code is not optimized though and will need to be tested deeply. Feel free to test it on your side if you have a moment. ;)

**Comment by niamtokik** [comment]
@philipcristiano It has been merged today. An article is available in `notes` to explain how this implementation is working.

**Comment by philipcristiano** [comment]
Awesome! I'll take a look!
